FROM node:16-alpine3.14 AS build-stage
WORKDIR /app/
COPY --chown=app:app package*.json ./
RUN  npm install
COPY --chown=app:app . .
ENV API_URL=http://api.myapp.com/
RUN npm run build

FROM nginx:1.12-alpine 
# RUN addgroup app && adduser -S -G app app
# USER app
COPY --from=build-stage /app/build /usr/share/nginx/html
EXPOSE 80
ENTRYPOINT [ "nginx", "-g", "daemon off;" ]